### ISSUE TITLE
Error: Failed to start the connection: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by engwalker** [rinukkusu/signalr2-dart#1]
I created a barebones app using the example code to test your interop and connect to my signalR server, I'm getting this 'Failed to start connection' error when calling connection.start that originates on line 2958 of the signalr.js script. I have all authentication removed from my test server, and have tried the url of my server both when running locally and not. It's not complaining about not finding /negotiate, so I should be hitting the proper location.

Could you provide some insight on this error? Thanks in advance!

**Comment by rinukkusu** [comment]
Hi Jeremy,

I just tried it real quick myself and everything looks good from here. I think the problem could be CORS related, when you're not running the Dart app and the WebAPI on the same domain/port. This always led to some trouble iirc.

You should be able to mitigate this with the following call in your `Startup.Configure` method:

```c#
app.UseCors(builder =>
{
    builder
        .AllowAnyHeader()
        .AllowAnyMethod()
        .AllowAnyOrigin()
        .AllowCredentials();
});
```

Obviously you can also finetune your allowed origins with the `builder.WithOrigins` method.

**Comment by rinukkusu** [comment]
Also which version of `Microsoft.AspNetCore.SignalR` do you have installed on your server? The current release on Pub is in sync with the version `1.0.0`. If you want to use `1.0.2` with Dart 2.0 you have to reference this git repository in your `pubspec.yaml` like that, [since I'm not able to push updates to Pub at the moment](https://github.com/dart-lang/pub-dartlang-dart/issues/1460):

```yaml
dependencies:
  signalr2:
    git: https://github.com/rinukkusu/signalr2-dart
```

EDIT: I just realized that there have been no changes on the js library from `1.0.0` to `1.0.2`, so this probably isn't the problem.

**Comment by engwalker** [comment]
I'll play around with Cors, but I already had all those options enabled and I'm getting connections and messages through using a javascript test client and a simpler Dart interop on two separate domains and when running locally. 

And actually now that I read through your second message and did a little searching, I'm running Microsoft.AspNet.SignalR and it looks like those clients/servers are incompatible. I had not realized that before and will be making a test AspNetCore server to test with. Thank you very much for looking at this with me!

**Comment by rinukkusu** [comment]
No problemo - glad I could help you! I hope you'll get your project up and running with .NET Core! 😄
