### ISSUE TITLE
Is there any updates to support flutter?

### ISSUE THREAD

**Issue by TareqNet3** [rinukkusu/signalr2-dart#2]
Hello

I'm trying to use **'signalr2-dart'** in a flutter project ([https://flutter.io](https://flutter.io))

When I add `import 'dart:js'` as the example in README, I'm getting this error:

> [dart] Target of URI doesn't exist: 'dart:js'.

Any updates to use this package with flutter?

Thanks!

**Comment by rinukkusu** [comment]
Hi Tareq,

sadly no, this project is just a wrapper around the [Javascript library](https://www.npmjs.com/package/@aspnet/signalr).

A while ago I saw this other issue on the SignalR repo itself: https://github.com/aspnet/SignalR/issues/2522
So it seems there are no native Dart implementations as of now.

Maybe you can start writing one? I'd be happy to contribute :smile:

**Comment by sir-boformer** [comment]
Would also be interested in writing one, but I guess it would be quite difficult to handle standby mode, reconnect etc.

**Comment by soernt** [comment]
Just to let you know. I started to implement a client. So far the WebSocketTransport and the ServerSideEventTransport is working within my Flutter app. I just started to implement the reamining LongPollingTransport. The JsonHubProtocol is implemented, I have no plan to implement the MessagePackHubProtocol. When I am done - I will let you know.

**Comment by soernt** [comment]
done :-)

https://pub.dartlang.org/packages/signalr_client
